name: Docker Build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'lesson_1/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'lesson_1/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./lesson_1
          load: true
          push: false
          tags: simple-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      # Add vulnerability scanning
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'simple-web:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
